#!/usr/bin/env bash

if [ $# -eq 0 ]; then
    echo "Usage: cwall <image>"
    exit 1
fi

image=$(realpath "$1")
config="$HOME/.config/hypr/hyprpaper.conf"

sed -i \
    -e "s|^preload = .*|preload = $image|" \
    -e "s|^wallpaper = .*|wallpaper = ,$image|" \
    "$config"

hyprctl hyprpaper wallpaper ",$image"
